export enum BeaconActionTypes {
  BEACON_REQUEST='BEACON_REQUEST',
  BEACON_REQUEST_PENDING='BEACON_REQUEST_PENDING',
  BEACON_REQUEST_SUCCESS='BEACON_REQUEST_SUCCESS',
  BEACON_REQUEST_ERROR='BEACON_REQUEST_ERROR',
}
